config/routes.rb
Rails.application.routes.draw do

  root "pizzas#index"
  resources :promotions
  resources :discounts
  resources :orders
  resources :ingrediants
  resources :pizzas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
end

app/models/pizza.rb
class Pizza < ApplicationRecord
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: %i[ show edit update destroy ]

  # GET /pizzas or /pizzas.json
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1 or /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas or /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to pizza_url(@pizza), notice: "Pizza was successfully created." }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1 or /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to pizza_url(@pizza), notice: "Pizza was successfully updated." }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1 or /pizzas/1.json
  def destroy
    @pizza.destroy!

    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: "Pizza was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pizza_params
      params.require(:pizza).permit(:name, :price, :size)
    end
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/pizzas/_form.html.erb
<%= form_with(model: pizza) do |form| %>
  <% if pizza.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
        <% pizza.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>


  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.text_field :size %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pizzas/_pizza.html.erb
<div id="<%= dom_id pizza %>">
  <p>
    <strong>Name:</strong>
    <%= pizza.name %>
  </p>

  <p>
  <strong>size:</strong>
  <%= pizza.size %>
</p>

  <p>
    <strong>Price:</strong>
    <%= pizza.price %>
  </p>

</div>

app/views/pizzas/edit.html.erb
<h1>Editing pizza</h1>

<%= render "form", pizza: @pizza %>

<br>

<div>
  <%= link_to "Show this pizza", @pizza %> |
  <%= link_to "Back to pizzas", pizzas_path %>
</div>

app/views/pizzas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pizzas</h1>

<div id="pizzas">
  <% @pizzas.each do |pizza| %>
    <%= render pizza %>
    <p>
      <%= link_to "Show this pizza", pizza %>
    </p>
  <% end %>
</div>

<%= link_to "New pizza", new_pizza_path %>

app/views/pizzas/new.html.erb
<h1>New pizza</h1>

<%= render "form", pizza: @pizza %>

<br>

<div>
  <%= link_to "Back to pizzas", pizzas_path %>
</div>

app/views/pizzas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pizza %>

<div>
  <%= link_to "Edit this pizza", edit_pizza_path(@pizza) %> |
  <%= link_to "Back to pizzas", pizzas_path %>

  <%= button_to "Destroy this pizza", @pizza, method: :delete %>
</div>