config/routes.rb
Rails.application.routes.draw do

  root "pizzas#index"
  resources :promotions
  resources :discounts
  resources :orders
  resources :ingrediants
  resources :pizzas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
end

app/models/discount.rb
class Discount < ApplicationRecord
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  before_action :set_discount, only: %i[ show edit update destroy ]

  # GET /discounts or /discounts.json
  def index
    @discounts = Discount.all
  end

  # GET /discounts/1 or /discounts/1.json
  def show
  end

  # GET /discounts/new
  def new
    @discount = Discount.new
  end

  # GET /discounts/1/edit
  def edit
  end

  # POST /discounts or /discounts.json
  def create
    @discount = Discount.new(discount_params)

    respond_to do |format|
      if @discount.save
        format.html { redirect_to discount_url(@discount), notice: "Discount was successfully created." }
        format.json { render :show, status: :created, location: @discount }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discounts/1 or /discounts/1.json
  def update
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to discount_url(@discount), notice: "Discount was successfully updated." }
        format.json { render :show, status: :ok, location: @discount }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounts/1 or /discounts/1.json
  def destroy
    @discount.destroy!

    respond_to do |format|
      format.html { redirect_to discounts_url, notice: "Discount was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount
      @discount = Discount.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def discount_params
      params.require(:discount).permit(:code, :discount_per)
    end
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/views/discounts/_discount.html.erb
<div id="<%= dom_id discount %>">
  <p>
    <strong>Code:</strong>
    <%= discount.code %>
  </p>

  <p>
    <strong>Discount per:</strong>
    <%= discount.discount_per %>
  </p>

</div>

app/views/discounts/_form.html.erb
<%= form_with(model: discount) do |form| %>
  <% if discount.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(discount.errors.count, "error") %> prohibited this discount from being saved:</h2>

      <ul>
        <% discount.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :discount_per, style: "display: block" %>
    <%= form.text_field :discount_per %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/discounts/edit.html.erb
<h1>Editing discount</h1>

<%= render "form", discount: @discount %>

<br>

<div>
  <%= link_to "Show this discount", @discount %> |
  <%= link_to "Back to discounts", discounts_path %>
</div>

app/views/discounts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Discounts</h1>

<div id="discounts">
  <% @discounts.each do |discount| %>
    <%= render discount %>
    <p>
      <%= link_to "Show this discount", discount %>
    </p>
  <% end %>
</div>

<%= link_to "New discount", new_discount_path %>

app/views/discounts/new.html.erb
<h1>New discount</h1>

<%= render "form", discount: @discount %>

<br>

<div>
  <%= link_to "Back to discounts", discounts_path %>
</div>

app/views/discounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @discount %>

<div>
  <%= link_to "Edit this discount", edit_discount_path(@discount) %> |
  <%= link_to "Back to discounts", discounts_path %>

  <%= button_to "Destroy this discount", @discount, method: :delete %>
</div>